#
# Copyright (c) 2018 Intel Corporation
# Copyright (c) 2018 IBM
#
# SPDX-License-Identifier: Apache-2.0
#

sudo: required
dist: xenial

language: go
os:
- linux
- linux-ppc64le
go_import_path: github.com/kata-containers/runtime

go:
  - "1.11.x"

env:
  - target_branch=$TRAVIS_BRANCH

before_install:
  - git remote set-branches --add origin "${TRAVIS_BRANCH}"
  - git fetch
  - ".ci/setup.sh"
  - ".ci/versions_checker.sh"

before_script:
  - ".ci/static-checks.sh"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - ".ci/install-yq.sh"
  - make
  - sudo -E PATH=$PATH make install
